### ISSUE TITLE
 No module named 'deepcell_retinamask.callbacks'

### ISSUE THREAD

**Issue by cuongnc220592** [vanvalenlab/deepcell-retinamask#6]
Hi author @willgraf 

I have an error when training: 
 
No module named 'deepcell_retinamask.callbacks'

I have installed deepcell-retinamask with
$ pip install deepcell-retinamask 

Can you help me how to fix this.
Thank you very much

**Comment by willgraf** [comment]
This should be fixed in the new 0.1.1 release (which should be ready on PyPI shortly). Please re-open the issue if it is not resolved.
